require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  CacheRootDirectory: tmp

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - Guardfile
    - lib/tasks/**/*.rb
    - config/**/*.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: error
